### ISSUE TITLE
Unity Scene: bio_ik with Python script

### ISSUE THREAD

**Issue by kavikode** [empriselab/RCareWorld#35]
After loading the example scene in bio_ik in Unity, there was no change in the scene after running the Python file example_bioik.py. There are no error messages either.

How can we resolve this?

**Comment by thisjustin123** [comment]
I tested around with this and found that there are a few configurations you need to do in order to get BioIK to work.

Since BioIK is a paid dependency that not everyone may have, we have blocked it off with a `BIOIK` directive we dynamically apply/remove at runtime depending on if the plugin is installed on one machine at the moment. However, I found a bug associated with checking this in our current codebase that may apply to yours as well.

Do you have the BioIK folder placed in `Assets/Plugins/BioIK`? This is how we are checking if BioIK is installed.

**Comment by kavikode** [comment]
Yes, it is in there. Still no movement.

**Comment by kavikode** [comment]
Thank you for your message!

Here is the screenshot of the BioIK folder:
![Screenshot Bio IK](https://github.com/empriselab/RCareWorld/assets/29847048/b6ec7c92-ae0f-41a6-92ca-db72f9510ea8)

Here is the screenshot of the Scripting Define Symbols box that I found in the Player menu:
![Scripting Define Symbols Screenshot](https://github.com/empriselab/RCareWorld/assets/29847048/e89f925e-3725-4a05-96f0-22a6f6a0cfdf)

Will you please let me know where I can find the file for the CheckPlugins.cs script?

**Comment by YoruCathy** [comment]
This is deprecated.
